### PR TITLE
Display error message when connecting wrong Xero

### PR DESCRIPTION
**Pull request by fgourichon**
@ouranos for review

### CODE REVIEW

**Comment by fgourichon** [comment]
image
@alexnoox I get an encoding issue when testing locally (code is the same as in mnoe). Any idea?

**Comment by alexnoox** [comment]
@fgourichon I never saw this. `&#34;` is a double quote`"`. Do you think it is coming from the toastr template or the variable value?

**Comment by fgourichon** [comment]
It might come from the variable as the message string is passed in the url, and " is encoded as %5C%22, which is \" so there is an escape \ which gets introduced at some point. But the mechanism and the code (toastr template and js) used is exactly the same as in mnoe, and we don't have this issue.

**Comment by ouranos** [comment]
@fgourichon Is there any difference in the components versions (`angular-translate`, `angular-translate-interpolation-messageformat`, ...)?

**Comment by fgourichon** [comment]
Yes. On the one looking relevant:
- angular-toaster is ~1.7.0 on mnoe and ~2.1.1 on admin
- angular-translate-xxx is ~2.14.0 on mnoe and ^2.14.0 on admin (current version is 2.15.1)

angular and angular-messages are ~1.6.0 on mnoe and ~1.6.2 on admin, so their should be no difference

I'll do some additional tests to see if it comes from here.

**Comment by fgourichon** [comment]
@ouranos @alexnoox I tried to downgrade dependencies to be iso with mnoe-angular, but no luck with that.
Also tried to build mnoe-admin within an express and it did not work either.
Workaround: I changed the error message in mnoe to replace " by ' and now it is working

**Pull request merged**
