### PR TITLE
Remove unused component

### PR DESCRIPTION
**Pull request by ouranos**
* Remove duplicates queries. 66% perf improvement....
* Remove obsolete component (which also had perf issues)

### CODE REVIEW

**Comment by ouranos** [comment]
Tagging everyone here to avoid the same issues in the future :)

Please keep an eye open on the inspector during development to spot suspicious behavior like this.

See also #171 and a7e343bf622bd4 for different root causes for the same issues

**Comment by iseessel** [comment]
I think problem was that angular-smart-tables automatically calls st-pipe upon initial rendering.

**Comment by iseessel** [comment]
@BrunoChauvet @ouranos Turns out this doesn't work -- when navigating from another page ctrl.organization is nil and method never gets hit again. Looking into a solution.

**Comment by ouranos** [comment]
@iseessel edited the PR to only remove the useless table as you fixed the perf issue in https://github.com/maestrano/mnoe-admin-panel/pull/264/commits/9460bc1efe6f445c5c8a9e49f48e30e30a2af8d5

**Pull request merged**
